---
AWSTemplateFormatVersion: '2010-09-09'
Description: Magento 2.1 Elasticsearch Template (gluo)
Parameters:
  DomainName:
    Description: User-defined Elasticsearch domain name
    Type: String
    Default: 'magento'
  ElasticsearchVersion:
    Description: User-defined Elasticsearch version
    Type: String
    Default: '7.10'
  InstanceType:
    Description: Elasticsearch Instance Type
    Type: String
    Default: 'm3.medium.elasticsearch'
  InstanceCount:
    Description: Elasticsearch Instance Count
    Type: String
    Default: '1'
  PrincipalArn:
    Description: Elasticsearch IAM User
    Type: String
    Default: 'arn:aws:iam::292242131230:user/ward.vandenbroeck@gluo.be'
  EBSIops:
    Description: Elasticsearch EBS iops
    Type: Number
    Default: 0
  EBSVolumeSize:
    Description: Elasticsearch EBS volume size (GB)
    Type: Number
    Default: 20
  EBSVolumeType:
    Description: Elasticsearch EBS volume type
    Type: String
    Default: "gp2"
  ESSubnetIds:
    Description: Elasticsearch Subnets
    Type: AWS::EC2::Subnet::Id
  ESSecurityGroupIds:
    Description: Elasticsearch SecurityGroups
    Type: AWS::EC2::SecurityGroup::Id
Resources:
  ElasticsearchDomain:
    Type: 'AWS::Elasticsearch::Domain'
    Properties:
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              AWS: !Ref PrincipalArn
            Action: 'es:*'
            Resource: 'arn:aws:logs:eu-central-1:292242131230:domain/*'
      AdvancedOptions: 
        rest.action.multi.allow_explicit_index: 'true'
      DomainName: !Ref DomainName
      EBSOptions:
        EBSEnabled: true
        Iops: !Ref EBSIops
        VolumeSize: !Ref EBSVolumeSize
        VolumeType: !Ref EBSVolumeType
      ElasticsearchClusterConfig: 
        DedicatedMasterEnabled: false
        InstanceCount: !Ref InstanceCount
        ZoneAwarenessEnabled: false
        InstanceType: !Ref InstanceType
        #DedicatedMasterType: !Ref InstanceType
        #DedicatedMasterCount: !Ref DedicatedMasterCount
      ElasticsearchVersion: !Ref ElasticsearchVersion
      LogPublishingOptions: 
        ES_APPLICATION_LOGS:
            Enabled: false
            #CloudWatchLogsLogGroupArn: 'arn:aws:logs:eu-central-1:292242131230:log-group:/aws/aes/domains/es-application-logs'
        SEARCH_SLOW_LOGS:
            Enabled: false
            #CloudWatchLogsLogGroupArn: 'arn:aws:logs:eu-central-1:292242131230:log-group:/aws/aes/domains/es-slow-logs'
        INDEX_SLOW_LOGS:
            Enabled: false
            #CloudWatchLogsLogGroupArn: 'arn:aws:logs:eu-central-1:292242131230:log-group:/aws/aes/domains/es-index-slow-logs'
      Tags: 
      - Key: solution
        Value: magento
      - Key: team
        Value: gluo
      VPCOptions: 
        SubnetIds:
          - !Ref ESSubnetIds
        SecurityGroupIds:
          - !Ref ESSecurityGroupIds    
      #AdvancedSecurityOptions: 
      #  AdvancedSecurityOptionsInput
      #CognitoOptions: 
      #  CognitoOptions
      #DomainEndpointOptions: 
      #  DomainEndpointOptions
      #EncryptionAtRestOptions: 
      #  EncryptionAtRestOptions
      #NodeToNodeEncryptionOptions: 
      #  NodeToNodeEncryptionOptions
      #SnapshotOptions: 
      #  SnapshotOptions
#Outputs:
#  ElastiCacheEndpoint:
#    Description: ElastiCache address
#    Value: !GetAtt ElastiCacheCluster.PrimaryEndPoint.Address
#...
